//! Safe surface implemented by Task Scheduler COM handler DLLs.

use std::{
    sync::{
        Arc,
        atomic::{AtomicBool, AtomicU8, Ordering},
    },
    thread,
    time::Duration,
};

use crate::Result;

/// User implementation executed on a background thread generated by
/// [`handler`](macro@crate::handler).
pub trait TaskHandler: Default + Send + 'static {
    /// Executes one task invocation. Observe `context.control` cooperatively and
    /// return after cancellation is requested.
    fn run(self, context: HandlerContext) -> Result<()>;
}

/// Data and services available during one handler invocation.
#[derive(Clone, Debug)]
pub struct HandlerContext {
    /// Opaque `<Data>` supplied by the ComHandler action.
    pub data: Option<String>,
    /// Cooperative pause/resume/stop state.
    pub control: HandlerControl,
    /// Thread-safe progress and completion reporter.
    pub reporter: ProgressReporter,
}

/// Cooperative control token updated by COM Pause, Resume, and Stop calls.
#[derive(Clone, Debug, Default)]
pub struct HandlerControl {
    state: Arc<AtomicU8>,
}

impl HandlerControl {
    /// Whether stop has been requested.
    #[must_use]
    pub fn is_cancelled(&self) -> bool {
        self.state.load(Ordering::Acquire) == 2
    }

    /// Whether execution is currently paused.
    #[must_use]
    pub fn is_paused(&self) -> bool {
        self.state.load(Ordering::Acquire) == 1
    }

    /// Blocks cooperatively while paused, returning once resumed or stopped.
    pub fn wait_if_paused(&self) {
        while self.is_paused() {
            thread::park_timeout(Duration::from_millis(25));
        }
    }

    #[doc(hidden)]
    pub fn request_pause(&self) {
        self.state.store(1, Ordering::Release);
    }

    #[doc(hidden)]
    pub fn request_resume(&self) {
        self.state.store(0, Ordering::Release);
    }

    #[doc(hidden)]
    pub fn request_stop(&self) {
        self.state.store(2, Ordering::Release);
    }
}

/// Reporter that accepts monotonic progress until completion.
#[derive(Clone, Debug, Default)]
pub struct ProgressReporter {
    completed: Arc<AtomicBool>,
    progress: Arc<AtomicU8>,
    #[cfg(windows)]
    native: Option<Arc<__native::NativeReporter>>,
}

impl ProgressReporter {
    /// Reports progress from zero through one hundred.
    pub fn report(&self, percent: u8) -> Result<()> {
        self.report_with_message(percent, "")
    }

    /// Reports monotonic progress with an optional status message.
    pub fn report_with_message(&self, percent: u8, message: &str) -> Result<()> {
        if percent > 100 {
            return Err(crate::Error::new(
                crate::ErrorKind::InvalidDefinition,
                "handler progress must be between 0 and 100",
            ));
        }
        if self.completed.load(Ordering::Acquire) {
            return Err(crate::Error::new(
                crate::ErrorKind::Conflict,
                "handler already completed",
            ));
        }
        let previous = self.progress.fetch_max(percent, Ordering::AcqRel);
        #[cfg(windows)]
        if percent > previous {
            if let Some(native) = &self.native {
                native.update(percent, message)?;
            }
        }
        #[cfg(not(windows))]
        {
            let _ = previous;
            let _ = message;
        }
        Ok(())
    }

    /// Returns the latest monotonic progress value.
    #[must_use]
    pub fn progress(&self) -> u8 {
        self.progress.load(Ordering::Acquire)
    }

    /// Marks completion exactly once.
    pub fn complete(&self) -> Result<()> {
        self.completed
            .compare_exchange(false, true, Ordering::AcqRel, Ordering::Acquire)
            .map_err(|_| {
                crate::Error::new(
                    crate::ErrorKind::Conflict,
                    "handler completion was already reported",
                )
            })?;
        #[cfg(windows)]
        if let Some(native) = &self.native {
            if let Err(error) = native.complete() {
                self.completed.store(false, Ordering::Release);
                return Err(error);
            }
        }
        Ok(())
    }
}

/// Native COM implementation used by the [`handler`](macro@crate::handler) macro.
#[cfg(windows)]
#[doc(hidden)]
pub mod __native {
    #![allow(
        unsafe_code,
        reason = "COM vtables, DLL exports, and marshaled interface pointers require native ABI code"
    )]
    #![allow(
        non_snake_case,
        reason = "windows-rs implementation traits retain COM method names"
    )]
    #![allow(
        trivial_casts,
        reason = "windows-core's implement macro emits vtable identity casts"
    )]
    #![allow(
        clippy::borrow_as_ptr,
        clippy::inline_always,
        clippy::not_unsafe_ptr_arg_deref,
        clippy::ptr_as_ptr,
        clippy::ref_as_ptr,
        clippy::needless_pass_by_value,
        reason = "windows-core generates the casts/inlining; validated raw ABI pointers stay inside this module"
    )]

    use std::{
        ffi::c_void,
        marker::PhantomData,
        mem::ManuallyDrop,
        panic::{AssertUnwindSafe, catch_unwind},
        sync::{
            Arc,
            atomic::{AtomicBool, AtomicUsize, Ordering},
            mpsc,
        },
        thread,
    };

    use windows::{
        Win32::{
            Foundation::{
                CLASS_E_CLASSNOTAVAILABLE, CLASS_E_NOAGGREGATION, E_FAIL, E_POINTER, S_FALSE, S_OK,
            },
            System::{
                Com::{
                    COINIT_MULTITHREADED, CoInitializeEx, CoUninitialize, IClassFactory,
                    IClassFactory_Impl, IStream, Marshal::CoMarshalInterThreadInterfaceInStream,
                    StructuredStorage::CoGetInterfaceAndReleaseStream,
                },
                TaskScheduler::{ITaskHandler, ITaskHandler_Impl, ITaskHandlerStatus},
            },
        },
        core::{BOOL, BSTR, Error as WindowsError, GUID, HRESULT, IUnknown, Interface, Ref},
    };
    use windows_core::implement;

    use super::{HandlerContext, HandlerControl, ProgressReporter, TaskHandler};

    /// ABI GUID type used in generated exports.
    pub type Guid = GUID;
    /// ABI HRESULT type used in generated exports.
    pub type HResult = HRESULT;

    static MODULE_OBJECTS: AtomicUsize = AtomicUsize::new(0);
    static SERVER_LOCKS: AtomicUsize = AtomicUsize::new(0);
    static ACTIVE_WORKERS: AtomicUsize = AtomicUsize::new(0);

    #[derive(Debug)]
    enum StatusCommand {
        Update {
            percent: u8,
            message: String,
            reply: mpsc::SyncSender<crate::Result<()>>,
        },
        Complete {
            reply: mpsc::SyncSender<crate::Result<()>>,
        },
        HandlerDone(crate::Result<()>),
    }

    #[derive(Debug)]
    pub(crate) struct NativeReporter {
        sender: mpsc::Sender<StatusCommand>,
    }

    impl NativeReporter {
        pub(crate) fn update(&self, percent: u8, message: &str) -> crate::Result<()> {
            let (reply, receiver) = mpsc::sync_channel(1);
            self.sender
                .send(StatusCommand::Update {
                    percent,
                    message: message.to_owned(),
                    reply,
                })
                .map_err(|_| reporter_stopped())?;
            receiver.recv().map_err(|_| reporter_stopped())?
        }

        pub(crate) fn complete(&self) -> crate::Result<()> {
            let (reply, receiver) = mpsc::sync_channel(1);
            self.sender
                .send(StatusCommand::Complete { reply })
                .map_err(|_| reporter_stopped())?;
            receiver.recv().map_err(|_| reporter_stopped())?
        }
    }

    #[allow(trivial_casts, reason = "generated by windows-core's implement macro")]
    #[implement(ITaskHandler)]
    struct NativeTaskHandler<T>
    where
        T: TaskHandler,
    {
        control: HandlerControl,
        running: Arc<AtomicBool>,
        marker: PhantomData<fn() -> T>,
    }

    impl<T: TaskHandler> NativeTaskHandler<T> {
        fn new() -> Self {
            MODULE_OBJECTS.fetch_add(1, Ordering::AcqRel);
            Self {
                control: HandlerControl::default(),
                running: Arc::new(AtomicBool::new(false)),
                marker: PhantomData,
            }
        }
    }

    impl<T: TaskHandler> Drop for NativeTaskHandler<T> {
        fn drop(&mut self) {
            MODULE_OBJECTS.fetch_sub(1, Ordering::AcqRel);
        }
    }

    impl<T: TaskHandler> ITaskHandler_Impl for NativeTaskHandler_Impl<T> {
        fn Start(&self, services: Ref<'_, IUnknown>, data: &BSTR) -> windows::core::Result<()> {
            self.running
                .compare_exchange(false, true, Ordering::AcqRel, Ordering::Acquire)
                .map_err(|_| WindowsError::from_hresult(E_FAIL))?;
            self.control.request_resume();
            let prepared = (|| {
                let data = String::try_from(data.clone())?;
                let status: ITaskHandlerStatus = services.ok()?.cast()?;
                let stream = unsafe {
                    CoMarshalInterThreadInterfaceInStream(&ITaskHandlerStatus::IID, &status)
                }?;
                Ok::<_, WindowsError>((
                    stream.into_raw() as usize,
                    (!data.is_empty()).then_some(data),
                ))
            })();
            let (stream_raw, data) = match prepared {
                Ok(prepared) => prepared,
                Err(error) => {
                    self.running.store(false, Ordering::Release);
                    return Err(error);
                }
            };
            let control = self.control.clone();
            let running = Arc::clone(&self.running);
            ACTIVE_WORKERS.fetch_add(1, Ordering::AcqRel);
            let spawned = thread::Builder::new()
                .name("windows-task-handler".into())
                .spawn(move || handler_worker::<T>(stream_raw, data, control, running));
            if spawned.is_err() {
                ACTIVE_WORKERS.fetch_sub(1, Ordering::AcqRel);
                self.running.store(false, Ordering::Release);
                drop(unsafe { IStream::from_raw(stream_raw as *mut c_void) });
                return Err(WindowsError::from_hresult(E_FAIL));
            }
            Ok(())
        }

        fn Stop(&self) -> windows::core::Result<HRESULT> {
            self.control.request_stop();
            Ok(S_OK)
        }

        fn Pause(&self) -> windows::core::Result<()> {
            self.control.request_pause();
            Ok(())
        }

        fn Resume(&self) -> windows::core::Result<()> {
            self.control.request_resume();
            Ok(())
        }
    }

    struct WorkerGuard {
        running: Arc<AtomicBool>,
    }

    impl Drop for WorkerGuard {
        fn drop(&mut self) {
            self.running.store(false, Ordering::Release);
            ACTIVE_WORKERS.fetch_sub(1, Ordering::AcqRel);
        }
    }

    fn handler_worker<T: TaskHandler>(
        stream_raw: usize,
        data: Option<String>,
        control: HandlerControl,
        running: Arc<AtomicBool>,
    ) {
        let _worker = WorkerGuard { running };
        let Ok(apartment) = ComApartment::initialize() else {
            drop(unsafe { IStream::from_raw(stream_raw as *mut c_void) });
            return;
        };
        let stream = ManuallyDrop::new(unsafe { IStream::from_raw(stream_raw as *mut c_void) });
        let Ok(status) =
            (unsafe { CoGetInterfaceAndReleaseStream::<_, ITaskHandlerStatus>(&*stream) })
        else {
            drop(apartment);
            return;
        };
        let (sender, receiver) = mpsc::channel();
        let reporter = ProgressReporter {
            completed: Arc::new(AtomicBool::new(false)),
            progress: Arc::new(std::sync::atomic::AtomicU8::new(0)),
            native: Some(Arc::new(NativeReporter {
                sender: sender.clone(),
            })),
        };
        let completed = Arc::clone(&reporter.completed);
        let context = HandlerContext {
            data,
            control,
            reporter,
        };
        let done_sender = sender.clone();
        let user = thread::Builder::new()
            .name("windows-task-handler-user".into())
            .spawn(move || {
                let result = T::default().run(context);
                if done_sender
                    .send(StatusCommand::HandlerDone(result))
                    .is_err()
                {
                    // The COM status worker has already terminated.
                }
            });
        drop(sender);
        let Ok(user) = user else {
            drop(unsafe { status.TaskCompleted(E_FAIL) });
            return;
        };
        let mut received_handler_done = false;
        while let Ok(command) = receiver.recv() {
            match command {
                StatusCommand::Update {
                    percent,
                    message,
                    reply,
                } => {
                    let result =
                        unsafe { status.UpdateStatus(i16::from(percent), &BSTR::from(message)) }
                            .map_err(|error| status_error("update handler status", error));
                    if reply.send(result).is_err() {
                        // The caller no longer needs the response.
                    }
                }
                StatusCommand::Complete { reply } => {
                    let result = unsafe { status.TaskCompleted(S_OK) }
                        .map_err(|error| status_error("complete handler task", error));
                    if result.is_err() {
                        // Let the final HandlerDone command retry completion. Resetting
                        // before the reply also closes the race with the user thread.
                        completed.store(false, Ordering::Release);
                    }
                    if reply.send(result).is_err() {
                        // The caller no longer needs the response.
                    }
                }
                StatusCommand::HandlerDone(result) => {
                    received_handler_done = true;
                    if !completed.swap(true, Ordering::AcqRel) {
                        let code = match result {
                            Ok(()) => S_OK,
                            Err(error) => error
                                .native_code()
                                .filter(|code| *code < 0)
                                .map_or(E_FAIL, HRESULT),
                        };
                        drop(unsafe { status.TaskCompleted(code) });
                    }
                    break;
                }
            }
        }
        let joined = user.join();
        if (!received_handler_done || joined.is_err()) && !completed.swap(true, Ordering::AcqRel) {
            drop(unsafe { status.TaskCompleted(E_FAIL) });
        }
        drop(apartment);
    }

    struct ComApartment;

    impl ComApartment {
        fn initialize() -> windows::core::Result<Self> {
            unsafe { CoInitializeEx(None, COINIT_MULTITHREADED) }.ok()?;
            Ok(Self)
        }
    }

    impl Drop for ComApartment {
        fn drop(&mut self) {
            unsafe { CoUninitialize() };
        }
    }

    #[allow(trivial_casts, reason = "generated by windows-core's implement macro")]
    #[implement(IClassFactory)]
    struct NativeClassFactory<T>
    where
        T: TaskHandler,
    {
        marker: PhantomData<fn() -> T>,
    }

    impl<T: TaskHandler> NativeClassFactory<T> {
        fn new() -> Self {
            MODULE_OBJECTS.fetch_add(1, Ordering::AcqRel);
            Self {
                marker: PhantomData,
            }
        }
    }

    impl<T: TaskHandler> Drop for NativeClassFactory<T> {
        fn drop(&mut self) {
            MODULE_OBJECTS.fetch_sub(1, Ordering::AcqRel);
        }
    }

    impl<T: TaskHandler> IClassFactory_Impl for NativeClassFactory_Impl<T> {
        fn CreateInstance(
            &self,
            outer: Ref<'_, IUnknown>,
            iid: *const GUID,
            output: *mut *mut c_void,
        ) -> windows::core::Result<()> {
            if !outer.is_null() {
                return Err(WindowsError::from_hresult(CLASS_E_NOAGGREGATION));
            }
            if iid.is_null() || output.is_null() {
                return Err(WindowsError::from_hresult(E_POINTER));
            }
            unsafe { output.write(std::ptr::null_mut()) };
            let handler: ITaskHandler = NativeTaskHandler::<T>::new().into();
            unsafe { handler.query(iid, output) }.ok()
        }

        fn LockServer(&self, lock: BOOL) -> windows::core::Result<()> {
            if lock.as_bool() {
                SERVER_LOCKS.fetch_add(1, Ordering::AcqRel);
            } else if SERVER_LOCKS
                .fetch_update(Ordering::AcqRel, Ordering::Acquire, |value| {
                    value.checked_sub(1)
                })
                .is_err()
            {
                // COM issued an unmatched unlock; keep the count at zero.
            }
            Ok(())
        }
    }

    /// Creates a class factory for the macro-selected handler type.
    pub fn dll_get_class_object<T: TaskHandler>(
        expected: GUID,
        requested: *const GUID,
        iid: *const GUID,
        output: *mut *mut c_void,
    ) -> HRESULT {
        catch_unwind(AssertUnwindSafe(|| {
            if requested.is_null() || iid.is_null() || output.is_null() {
                return E_POINTER;
            }
            unsafe { output.write(std::ptr::null_mut()) };
            if unsafe { *requested } != expected {
                return CLASS_E_CLASSNOTAVAILABLE;
            }
            let factory: IClassFactory = NativeClassFactory::<T>::new().into();
            unsafe { factory.query(iid, output) }
        }))
        .unwrap_or(E_FAIL)
    }

    /// Reports whether COM may unload the handler DLL.
    pub fn dll_can_unload_now() -> HRESULT {
        if MODULE_OBJECTS.load(Ordering::Acquire) == 0
            && SERVER_LOCKS.load(Ordering::Acquire) == 0
            && ACTIVE_WORKERS.load(Ordering::Acquire) == 0
        {
            S_OK
        } else {
            S_FALSE
        }
    }

    fn reporter_stopped() -> crate::Error {
        crate::Error::new(
            crate::ErrorKind::WorkerStopped,
            "Task Scheduler handler status worker stopped",
        )
    }

    fn status_error(operation: &str, error: WindowsError) -> crate::Error {
        crate::Error::new(crate::ErrorKind::Com, error.message())
            .with_operation(operation)
            .with_native_code(error.code().0)
    }
}
